services:
  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - HUBSPOT_API_KEY=${HUBSPOT_API_KEY}
      - HUBSPOT_FORM_URL=${HUBSPOT_FORM_URL}
    volumes:
      - sqlite_data:/app/data
    networks:
      - plg-network

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - plg-network

  streamlit:
    build: 
      context: ./streamlit-simulator
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - plg-network

networks:
  plg-network:
    driver: bridge

volumes:
  sqlite_data: 
